// <auto-generated />
using System;
using LancacheManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LancacheManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108155457_AddCachedServiceDetections")]
    partial class AddCachedServiceDetections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LancacheManager.Models.BlizzardChunkMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ByteOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveIndex")
                        .HasDatabaseName("IX_BlizzardChunkMappings_ArchiveIndex");

                    b.HasIndex("Product")
                        .HasDatabaseName("IX_BlizzardChunkMappings_Product");

                    b.HasIndex("Product", "ArchiveIndex", "ByteOffset")
                        .IsUnique()
                        .HasDatabaseName("IX_BlizzardChunkMappings_ProductArchiveOffset");

                    b.ToTable("BlizzardChunkMappings");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedGameDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepotIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("GameAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameAppId")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedGameDetection_GameAppId");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedGameDetection_LastDetectedUtc");

                    b.ToTable("CachedGameDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedServiceDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedServiceDetection_LastDetectedUtc");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedServiceDetection_ServiceName");

                    b.ToTable("CachedServiceDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientStats", b =>
                {
                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientIp");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ClientStats_LastActivityUtc");

                    b.ToTable("ClientStats");
                });

            modelBuilder.Entity("LancacheManager.Models.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlizzardArchiveIndex")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("BlizzardByteOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlizzardFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlizzardProduct")
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("GameAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTimeUtc")
                        .HasDatabaseName("IX_Downloads_EndTime");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Downloads_IsActive");

                    b.HasIndex("StartTimeUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Downloads_StartTime");

                    b.HasIndex("ClientIp", "Service", "IsActive")
                        .HasDatabaseName("IX_Downloads_Client_Service_Active");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesServed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DownloadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId")
                        .HasDatabaseName("IX_LogEntries_DownloadId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LogEntries_Timestamp");

                    b.HasIndex("ClientIp", "Service")
                        .HasDatabaseName("IX_LogEntries_Client_Service");

                    b.HasIndex("ClientIp", "Service", "Timestamp", "Url", "BytesServed")
                        .HasDatabaseName("IX_LogEntries_DuplicateCheck");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LancacheManager.Models.ServiceStats", b =>
                {
                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("Service");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ServiceStats_LastActivityUtc");

                    b.ToTable("ServiceStats");
                });

            modelBuilder.Entity("LancacheManager.Models.SteamDepotMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("IX_SteamDepotMappings_AppId");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId");

                    b.HasIndex("DepotId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId_AppId");

                    b.ToTable("SteamDepotMappings");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.HasOne("LancacheManager.Models.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId");

                    b.Navigation("Download");
                });
#pragma warning restore 612, 618
        }
    }
}
