// <auto-generated />
using System;
using LancacheManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LancacheManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104040012_RemoveUsernameHashColumns")]
    partial class RemoveUsernameHashColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("LancacheManager.Models.BannedSteamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BannedDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLifted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LiftedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiftedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BannedAtUtc")
                        .HasDatabaseName("IX_BannedSteamUsers_BannedAtUtc");

                    b.HasIndex("IsLifted")
                        .HasDatabaseName("IX_BannedSteamUsers_IsLifted");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_BannedSteamUsers_Username");

                    b.ToTable("BannedSteamUsers");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedCorruptionDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CorruptedChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedCorruptionDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedGameDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepotIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("GameAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameAppId")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedGameDetection_GameAppId");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedGameDetection_LastDetectedUtc");

                    b.ToTable("CachedGameDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedServiceDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedServiceDetection_LastDetectedUtc");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedServiceDetection_ServiceName");

                    b.ToTable("CachedServiceDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientGroups_Nickname");

                    b.ToTable("ClientGroups");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientGroupId")
                        .HasDatabaseName("IX_ClientGroupMembers_ClientGroupId");

                    b.HasIndex("ClientIp")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientGroupMembers_ClientIp");

                    b.ToTable("ClientGroupMembers");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientStats", b =>
                {
                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDurationSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("ClientIp");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ClientStats_LastActivityUtc");

                    b.ToTable("ClientStats");
                });

            modelBuilder.Entity("LancacheManager.Models.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Datasource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("GameAppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Datasource")
                        .HasDatabaseName("IX_Downloads_Datasource");

                    b.HasIndex("EndTimeUtc")
                        .HasDatabaseName("IX_Downloads_EndTime");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Downloads_IsActive");

                    b.HasIndex("StartTimeUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Downloads_StartTime");

                    b.HasIndex("ClientIp", "Service", "IsActive")
                        .HasDatabaseName("IX_Downloads_Client_Service_Active");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("LancacheManager.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTimeUtc")
                        .HasDatabaseName("IX_Events_EndTimeUtc");

                    b.HasIndex("StartTimeUtc")
                        .HasDatabaseName("IX_Events_StartTimeUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LancacheManager.Models.EventDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTagged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TaggedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId")
                        .HasDatabaseName("IX_EventDownloads_DownloadId");

                    b.HasIndex("TaggedAtUtc")
                        .HasDatabaseName("IX_EventDownloads_TaggedAtUtc");

                    b.HasIndex("EventId", "DownloadId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventDownloads_EventId_DownloadId");

                    b.ToTable("EventDownloads");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesServed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Datasource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DownloadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Datasource")
                        .HasDatabaseName("IX_LogEntries_Datasource");

                    b.HasIndex("DownloadId")
                        .HasDatabaseName("IX_LogEntries_DownloadId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LogEntries_Timestamp");

                    b.HasIndex("ClientIp", "Service")
                        .HasDatabaseName("IX_LogEntries_Client_Service");

                    b.HasIndex("ClientIp", "Service", "Timestamp", "Url", "BytesServed")
                        .HasDatabaseName("IX_LogEntries_DuplicateCheck");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrefilling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("IX_PrefillSessions_ContainerId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_PrefillSessions_CreatedAtUtc");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_PrefillSessions_DeviceId");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PrefillSessions_SessionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PrefillSessions_Status");

                    b.HasIndex("SteamUsername")
                        .HasDatabaseName("IX_PrefillSessions_SteamUsername");

                    b.ToTable("PrefillSessions");
                });

            modelBuilder.Entity("LancacheManager.Models.ServiceStats", b =>
                {
                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("Service");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ServiceStats_LastActivityUtc");

                    b.ToTable("ServiceStats");
                });

            modelBuilder.Entity("LancacheManager.Models.SteamDepotMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("DepotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepotName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("IX_SteamDepotMappings_AppId");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId");

                    b.HasIndex("DepotId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId_AppId");

                    b.ToTable("SteamDepotMappings");
                });

            modelBuilder.Entity("LancacheManager.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedTimeFormats")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableFocusOutlines")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableStickyNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DisableTooltips")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PicsAlwaysVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedTheme")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SharpCorners")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowDatasourceLabels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowYearInDates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Use24HourFormat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLocalTimezone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPreferences_DeviceId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LancacheManager.Models.UserSession", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PrefillEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PrefillExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_UserSessions_ExpiresAtUtc");

                    b.HasIndex("IsGuest")
                        .HasDatabaseName("IX_UserSessions_IsGuest");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("IX_UserSessions_IsRevoked");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("IX_UserSessions_LastSeenAtUtc");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroupMember", b =>
                {
                    b.HasOne("LancacheManager.Models.ClientGroup", "ClientGroup")
                        .WithMany("Members")
                        .HasForeignKey("ClientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientGroup");
                });

            modelBuilder.Entity("LancacheManager.Models.EventDownload", b =>
                {
                    b.HasOne("LancacheManager.Models.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LancacheManager.Models.Event", "Event")
                        .WithMany("EventDownloads")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.HasOne("LancacheManager.Models.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId");

                    b.Navigation("Download");
                });

            modelBuilder.Entity("LancacheManager.Models.UserPreferences", b =>
                {
                    b.HasOne("LancacheManager.Models.UserSession", "Session")
                        .WithOne("Preferences")
                        .HasForeignKey("LancacheManager.Models.UserPreferences", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LancacheManager.Models.Event", b =>
                {
                    b.Navigation("EventDownloads");
                });

            modelBuilder.Entity("LancacheManager.Models.UserSession", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
