// <auto-generated />
using System;
using LancacheManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LancacheManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LancacheManager.Models.BannedSteamUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BannedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BannedBySessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLifted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LiftedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiftedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BannedAtUtc")
                        .HasDatabaseName("IX_BannedSteamUsers_BannedAtUtc");

                    b.HasIndex("IsLifted")
                        .HasDatabaseName("IX_BannedSteamUsers_IsLifted");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_BannedSteamUsers_Username");

                    b.ToTable("BannedSteamUsers");
                });

            modelBuilder.Entity("LancacheManager.Models.CacheSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalCacheSize")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedCacheSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("IX_CacheSnapshots_TimestampUtc");

                    b.ToTable("CacheSnapshots");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedCorruptionDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CorruptedChunkCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CachedCorruptionDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedGameDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatasourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepotIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GameAppId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalSizeBytes")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GameAppId")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedGameDetection_GameAppId");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedGameDetection_LastDetectedUtc");

                    b.ToTable("CachedGameDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.CachedServiceDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheFilePathsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CacheFilesFound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatasourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastDetectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleUrlsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalSizeBytes")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("LastDetectedUtc")
                        .HasDatabaseName("IX_CachedServiceDetection_LastDetectedUtc");

                    b.HasIndex("ServiceName")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedServiceDetection_ServiceName");

                    b.ToTable("CachedServiceDetections");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientGroups_Nickname");

                    b.ToTable("ClientGroups");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClientGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientGroupId")
                        .HasDatabaseName("IX_ClientGroupMembers_ClientGroupId");

                    b.HasIndex("ClientIp")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientGroupMembers_ClientIp");

                    b.ToTable("ClientGroupMembers");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientStats", b =>
                {
                    b.Property<string>("ClientIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer");

                    b.Property<double>("TotalDurationSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("ClientIp");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ClientStats_LastActivityUtc");

                    b.ToTable("ClientStats");
                });

            modelBuilder.Entity("LancacheManager.Models.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CacheHitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("CacheMissBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Datasource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DepotId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EpicAppId")
                        .HasColumnType("text");

                    b.Property<long?>("GameAppId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastUrl")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Datasource")
                        .HasDatabaseName("IX_Downloads_Datasource");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("IX_Downloads_DepotId");

                    b.HasIndex("EndTimeUtc")
                        .HasDatabaseName("IX_Downloads_EndTime");

                    b.HasIndex("EpicAppId")
                        .HasDatabaseName("IX_Downloads_EpicAppId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Downloads_IsActive");

                    b.HasIndex("StartTimeUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_Downloads_StartTime");

                    b.HasIndex("ClientIp", "Service", "IsActive")
                        .HasDatabaseName("IX_Downloads_Client_Service_Active");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("LancacheManager.Models.EpicCdnPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CdnHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChunkBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("IX_EpicCdnPatterns_AppId");

                    b.HasIndex("ChunkBaseUrl")
                        .IsUnique()
                        .HasDatabaseName("IX_EpicCdnPatterns_ChunkBaseUrl");

                    b.ToTable("EpicCdnPatterns");
                });

            modelBuilder.Entity("LancacheManager.Models.EpicGameMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoveredByHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasDatabaseName("IX_EpicGameMappings_AppId");

                    b.HasIndex("DiscoveredAtUtc")
                        .HasDatabaseName("IX_EpicGameMappings_DiscoveredAtUtc");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_EpicGameMappings_Name");

                    b.ToTable("EpicGameMappings");
                });

            modelBuilder.Entity("LancacheManager.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EndTimeUtc")
                        .HasDatabaseName("IX_Events_EndTimeUtc");

                    b.HasIndex("StartTimeUtc")
                        .HasDatabaseName("IX_Events_StartTimeUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LancacheManager.Models.EventDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoTagged")
                        .HasColumnType("boolean");

                    b.Property<int>("DownloadId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TaggedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId")
                        .HasDatabaseName("IX_EventDownloads_DownloadId");

                    b.HasIndex("TaggedAtUtc")
                        .HasDatabaseName("IX_EventDownloads_TaggedAtUtc");

                    b.HasIndex("EventId", "DownloadId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventDownloads_EventId_DownloadId");

                    b.ToTable("EventDownloads");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BytesServed")
                        .HasColumnType("bigint");

                    b.Property<string>("CacheStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Datasource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("DepotId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DownloadId")
                        .HasColumnType("integer");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Datasource")
                        .HasDatabaseName("IX_LogEntries_Datasource");

                    b.HasIndex("DownloadId")
                        .HasDatabaseName("IX_LogEntries_DownloadId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LogEntries_Timestamp");

                    b.HasIndex("ClientIp", "Service")
                        .HasDatabaseName("IX_LogEntries_Client_Service");

                    b.HasIndex("ClientIp", "Service", "Timestamp", "Url", "BytesServed")
                        .HasDatabaseName("IX_LogEntries_DuplicateCheck");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillCachedDepot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<string>("AppName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CachedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("DepotId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ManifestId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("DepotId", "ManifestId")
                        .IsUnique();

                    b.ToTable("PrefillCachedDepots");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AppName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("BytesDownloaded")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("IX_PrefillHistoryEntries_AppId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_PrefillHistoryEntries_SessionId");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_PrefillHistoryEntries_StartedAtUtc");

                    b.ToTable("PrefillHistoryEntries");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBySessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrefilling")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Steam");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SteamUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerminatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("IX_PrefillSessions_ContainerId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_PrefillSessions_CreatedAtUtc");

                    b.HasIndex("CreatedBySessionId")
                        .HasDatabaseName("IX_PrefillSessions_CreatedBySessionId");

                    b.HasIndex("Platform")
                        .HasDatabaseName("IX_PrefillSessions_Platform");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_PrefillSessions_SessionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PrefillSessions_Status");

                    b.HasIndex("SteamUsername")
                        .HasDatabaseName("IX_PrefillSessions_SteamUsername");

                    b.ToTable("PrefillSessions");
                });

            modelBuilder.Entity("LancacheManager.Models.ServiceStats", b =>
                {
                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActivityLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalCacheHitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCacheMissBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer");

                    b.HasKey("Service");

                    b.HasIndex("LastActivityUtc")
                        .HasDatabaseName("IX_ServiceStats_LastActivityUtc");

                    b.ToTable("ServiceStats");
                });

            modelBuilder.Entity("LancacheManager.Models.SteamDepotMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.Property<long>("DepotId")
                        .HasColumnType("bigint");

                    b.Property<string>("DepotName")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("IX_SteamDepotMappings_AppId");

                    b.HasIndex("DepotId")
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId");

                    b.HasIndex("DepotId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("IX_SteamDepotMappings_DepotId_AppId");

                    b.ToTable("SteamDepotMappings");
                });

            modelBuilder.Entity("LancacheManager.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedTimeFormats")
                        .HasColumnType("text");

                    b.Property<bool>("DisableFocusOutlines")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableStickyNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisableTooltips")
                        .HasColumnType("boolean");

                    b.Property<int?>("EpicMaxThreadCount")
                        .HasColumnType("integer");

                    b.Property<bool>("PicsAlwaysVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshRate")
                        .HasColumnType("text");

                    b.Property<bool?>("RefreshRateLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("SelectedTheme")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SharpCorners")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowDatasourceLabels")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowYearInDates")
                        .HasColumnType("boolean");

                    b.Property<int?>("SteamMaxThreadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Use24HourFormat")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseLocalTimezone")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPreferences_SessionId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("LancacheManager.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EpicPrefillExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousSessionTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PreviousTokenValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SteamPrefillExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_UserSessions_ExpiresAtUtc");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("IX_UserSessions_IsRevoked");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_UserSessions_SessionTokenHash");

                    b.HasIndex("SessionType")
                        .HasDatabaseName("IX_UserSessions_SessionType");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroupMember", b =>
                {
                    b.HasOne("LancacheManager.Models.ClientGroup", "ClientGroup")
                        .WithMany("Members")
                        .HasForeignKey("ClientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientGroup");
                });

            modelBuilder.Entity("LancacheManager.Models.EventDownload", b =>
                {
                    b.HasOne("LancacheManager.Models.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LancacheManager.Models.Event", "Event")
                        .WithMany("EventDownloads")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Download");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("LancacheManager.Models.LogEntryRecord", b =>
                {
                    b.HasOne("LancacheManager.Models.Download", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadId");

                    b.Navigation("Download");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillHistoryEntry", b =>
                {
                    b.HasOne("LancacheManager.Models.PrefillSession", "Session")
                        .WithMany("PrefillHistory")
                        .HasForeignKey("SessionId")
                        .HasPrincipalKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LancacheManager.Models.UserPreferences", b =>
                {
                    b.HasOne("LancacheManager.Models.UserSession", "Session")
                        .WithOne("Preferences")
                        .HasForeignKey("LancacheManager.Models.UserPreferences", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LancacheManager.Models.ClientGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LancacheManager.Models.Event", b =>
                {
                    b.Navigation("EventDownloads");
                });

            modelBuilder.Entity("LancacheManager.Models.PrefillSession", b =>
                {
                    b.Navigation("PrefillHistory");
                });

            modelBuilder.Entity("LancacheManager.Models.UserSession", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
