[meta]
name = "Sage"
id = "sage"
description = "A calming green theme with earthy tones"
author = "LanCache Manager"
version = "1.0.0"
isDark = true

[colors]
# Core Colors
primaryColor = "#86efac"
secondaryColor = "#4ade80"
accentColor = "#22c55e"

# Background Layers
bgPrimary = "#0f1f14"
bgSecondary = "#1a2f1f"
bgTertiary = "#253d2a"
bgHover = "#2f4a35"

# Text Hierarchy
textPrimary = "#f0fdf4"
textSecondary = "#bbf7d0"
textMuted = "#86efac"
textAccent = "#4ade80"
textPlaceholder = "#4b7c5a"

# Navigation
navBg = "#1a2f1f"
navBorder = "#253d2a"
navTabActive = "#253d2a"
navTabInactive = "#86efac"
navTabHover = "#2f4a35"
navTabActiveBorder = "#4ade80"
navMobileMenuBg = "#1a2f1f"
navMobileItemHover = "#253d2a"

# Borders & Dividers
borderPrimary = "#253d2a"
borderSecondary = "#1a2f1f"
borderFocus = "#4ade80"

# Status Indicators
success = "#22c55e"
successBg = "#14532d"
successText = "#86efac"
successBorder = "#166534"

warning = "#eab308"
warningBg = "#713f12"
warningText = "#fef08a"
warningBorder = "#a16207"

error = "#ef4444"
errorBg = "#7f1d1d"
errorText = "#fca5a5"
errorBorder = "#dc2626"

info = "#3b82f6"
infoBg = "#1e3a8a"
infoText = "#93c5fd"
infoBorder = "#2563eb"

# Service Colors
steamColor = "#2563eb"
epicColor = "#7c3aed"
originColor = "#ea580c"
blizzardColor = "#06b6d4"
wsusColor = "#16a34a"
riotColor = "#dc2626"

# Component Styles
cardBg = "#1a2f1f"
cardBorder = "#253d2a"
buttonBg = "#22c55e"
buttonHover = "#16a34a"
buttonText = "#ffffff"
inputBg = "#1a2f1f"
inputBorder = "#253d2a"
inputFocus = "#4ade80"
checkboxAccent = "#4ade80"
checkboxBorder = "#253d2a"
sliderAccent = "#4ade80"
sliderThumb = "#86efac"
sliderTrack = "#253d2a"
badgeBg = "#253d2a"
badgeText = "#86efac"
progressBar = "#4ade80"
progressBg = "#1a2f1f"

# Hit Rate Colors
hitRateHighBg = "#14532d"
hitRateHighText = "#86efac"
hitRateMediumBg = "#713f12"
hitRateMediumText = "#fef08a"
hitRateLowBg = "#7c2d12"
hitRateLowText = "#fed7aa"
hitRateWarningBg = "#7f1d1d"
hitRateWarningText = "#fca5a5"

# Action Buttons
actionResetBg = "#3b82f6"
actionResetHover = "#2563eb"
actionProcessBg = "#22c55e"
actionProcessHover = "#16a34a"
actionDeleteBg = "#ef4444"
actionDeleteHover = "#dc2626"

# Icon Backgrounds
iconBgBlue = "#1e3a8a"
iconBgGreen = "#14532d"
iconBgEmerald = "#064e3b"
iconBgPurple = "#4c1d95"
iconBgIndigo = "#312e81"
iconBgOrange = "#7c2d12"
iconBgYellow = "#713f12"
iconBgCyan = "#164e63"
iconBgRed = "#7f1d1d"

# Chart Colors
chartColor1 = "#4ade80"
chartColor2 = "#22c55e"
chartColor3 = "#86efac"
chartColor4 = "#16a34a"
chartColor5 = "#bbf7d0"
chartColor6 = "#10b981"
chartColor7 = "#34d399"
chartColor8 = "#6ee7b7"
chartBorderColor = "#253d2a"
chartGridColor = "#1a2f1f"
chartTextColor = "#86efac"
chartCacheHitColor = "#22c55e"
chartCacheMissColor = "#ef4444"

# UI Elements
scrollbarTrack = "#1a2f1f"
scrollbarThumb = "#253d2a"
scrollbarHover = "#2f4a35"
dragHandleColor = "#4b7c5a"
dragHandleHover = "#86efac"

# Access Indicators
publicAccessBg = "#14532d"
publicAccessText = "#86efac"
publicAccessBorder = "#22c55e"
securedAccessBg = "#7c2d12"
securedAccessText = "#fed7aa"
securedAccessBorder = "#ea580c"

[css]
content = """
/* Sage theme custom styles */
.themed-card {
  border-radius: 8px;
  background: linear-gradient(135deg, rgba(26, 47, 31, 0.9), rgba(37, 61, 42, 0.9));
  backdrop-filter: blur(8px);
}

.stat-card {
  transition: all 0.3s ease;
}

.stat-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 16px rgba(34, 197, 94, 0.1);
}

button {
  border-radius: 6px;
  font-weight: 500;
  transition: all 0.2s ease;
}

button:hover {
  transform: scale(1.02);
  box-shadow: 0 4px 12px rgba(134, 239, 172, 0.2);
}

/* Subtle green glow for focus states */
input:focus,
select:focus,
textarea:focus {
  box-shadow: 0 0 0 3px rgba(74, 222, 128, 0.1);
}

/* Smooth scrollbar */
::-webkit-scrollbar-thumb {
  border-radius: 4px;
}

/* Chart enhancements */
.chart-container {
  border-radius: 8px;
  background: rgba(15, 31, 20, 0.5);
}
"""